name: ThreatGames
version: 1.0.0
main: com.thethreatgames.threatgames.Threatgames
api-version: 1.18
commands:
  AOMEI:
    description: Toggles the plugin!
    usage: /<command>

permissions:
  aomei.toggle:
    description: Permission for toggling the plugin, AKA Command /aomei
    default: false