name: ThreadGames
version: '${project.version}'
main: com.thethreadgames.threadgames.Threadgames
api-version: 1.18
commands:
  invclear:
    description: Clears the users inventory!
    usage: /<command>
  heal:
    description: Heals the user!
    usage: /<command>
  AOMEI:
    description: Toggles the plugin!
    usage: /<command>
